name: mobile_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.0-93.0.dev

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.3.0
  provider: ^6.1.5+1
  freezed: ^3.2.0
  json_serializable: ^6.11.0
  freezed_annotation: ^3.1.0
  shared_preferences: ^2.5.3
  go_router: ^16.2.1
  google_fonts: ^6.3.1
  font_awesome_flutter: ^10.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/google_logo.png
    - assets/appointments.json
